const { Client, GatewayIntentBits } = require('discord.js');
const client = new Client({
  intents: [
    GatewayIntentBits.Guilds,
    GatewayIntentBits.GuildMessages,
    GatewayIntentBits.MessageContent
  ]
});

// 300 punchlines de clash
const punchlines = [
"T’es tellement nul que même ton ombre te fuit.",
"T’es tellement froid que même un glaçon te trouve glacial.",
"T’es tellement lent que les tortues t’ont doublé en marchant.",
"T’es tellement moche que ton miroir te demande pardon.",
"T’es tellement idiot que Google refuse de répondre à tes questions.",
"T’es tellement ridicule que les clowns te prennent comme exemple.",
"T’es tellement faible que même les feuilles te repoussent.",
"T’es tellement maladroit que même les murs t’évitent.",
"T’es tellement paresseux que ton lit t’a envoyé un message de plainte.",
"T’es tellement con que Siri te dit 'non'.",
"T’es tellement nul que les zombies t’ignorent.",
"T’es tellement idiot que même ton chat te regarde avec pitié.",
"T’es tellement bizarre que les fantômes t’évitent.",
"T’es tellement fade que le sel refuse de t’accompagner.",
"T’es tellement lent que les limaces te dépassent.",
"T’es tellement nul que même les araignées te fuient.",
"T’es tellement faible que les sacs de riz te dominent.",
"T’es tellement moche que les pierres te rejettent.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement ridicule que les escargots te battent en course.",
"T’es tellement paresseux que le canapé te quitte.",
"T’es tellement con que ton réveil te fait des blagues.",
"T’es tellement nul que même ton Wi-Fi t’ignore.",
"T’es tellement froid que les glaciers te remercient.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement lent que même les escargots te rient au nez.",
"T’es tellement nul que même les ordinateurs te bloquent.",
"T’es tellement idiot que les intelligences artificielles te regardent bizarre.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement ridicule que les clowns se moquent de toi.",
"T’es tellement nul que les pigeons te fuient.",
"T’es tellement idiot que même ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement moche que les poupées ont peur de toi.",
"T’es tellement nul que ton réveil te réveille pour te dire 'stop'.",
"T’es tellement con que tu as besoin de GPS pour aller aux toilettes.",
"T’es tellement lent que même les escargots font la course contre toi et gagnent.",
"T’es tellement froid que les igloos te demandent conseil.",
"T’es tellement idiot que même les plantes ne veulent pas t’écouter.",
"T’es tellement moche que ton reflet se cache derrière un rideau.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement faible que même les moustiques t’attaquent en groupe.",
"T’es tellement ridicule que les clowns t’invitent à des cours de perfectionnement.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement con que ton téléphone t’ignore quand tu l’appelles.",
"T’es tellement nul que même ton chien refuse de te suivre.",
"T’es tellement bizarre que les fantômes t’ignorent.",
"T’es tellement fade que le sel te fuit.",
"T’es tellement lent que les limaces te doublent.",
"T’es tellement nul que même les araignées te craignent.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement ridicule que les escargots te battent au sprint.",
"T’es tellement paresseux que le canapé te quitte.",
"T’es tellement con que ton réveil te joue des tours.",
"T’es tellement nul que même ton Wi-Fi te bloque.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement lent que les escargots te doublent.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement idiot que les IA te regardent de travers.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que même les pigeons te fuient.",
"T’es tellement idiot que ton miroir se cache.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement nul que ton réveil te réveille pour te dire 'arrête'.",
"T’es tellement con que tu as besoin de GPS pour t’asseoir.",
"T’es tellement lent que les tortues te doublent en marchant.",
"T’es tellement froid que les igloos te demandent conseil.",
"T’es tellement idiot que même les plantes te fuient.",
"T’es tellement moche que ton reflet se cache derrière un rideau.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement faible que les moustiques t’attaquent.",
"T’es tellement ridicule que les clowns t’invitent à des cours.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement con que ton téléphone t’ignore.",
"T’es tellement nul que même ton chien refuse de te suivre.",
"T’es tellement bizarre que les fantômes t’ignorent.",
"T’es tellement fade que le sel te fuit.",
"T’es tellement lent que les limaces te doublent.",
"T’es tellement nul que même les araignées te craignent.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement ridicule que les escargots te battent au sprint.",
"T’es tellement paresseux que le canapé te quitte.",
"T’es tellement con que ton réveil te joue des tours.",
"T’es tellement nul que même ton Wi-Fi te bloque.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement lent que les escargots te doublent.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement idiot que les IA te regardent de travers.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que même les pigeons te fuient.",
"T’es tellement idiot que ton miroir se cache.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement nul que ton réveil te réveille pour te dire 'arrête'.",
"T’es tellement con que tu as besoin de GPS pour t’asseoir.",
"T’es tellement lent que les tortues te doublent en marchant.",
"T’es tellement froid que les igloos te demandent conseil.",
"T’es tellement idiot que même les plantes te fuient.",
"T’es tellement moche que ton reflet se cache derrière un rideau.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement faible que les moustiques t’attaquent.",
"T’es tellement ridicule que les clowns t’invitent à des cours.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement con que ton téléphone t’ignore.",
"T’es tellement nul que même ton chien refuse de te suivre.",
"T’es tellement bizarre que les fantômes t’ignorent.",
"T’es tellement fade que le sel te fuit.",
"T’es tellement lent que les limaces te doublent.",
"T’es tellement nul que même les araignées te craignent.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement ridicule que les escargots te battent au sprint.",
"T’es tellement paresseux que le canapé te quitte.",
"T’es tellement con que ton réveil te joue des tours.",
"T’es tellement nul que même ton Wi-Fi te bloque.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement lent que les escargots te doublent.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement idiot que les IA te regardent de travers.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que même les pigeons te fuient.",
"T’es tellement idiot que ton miroir se cache.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement nul que ton réveil te réveille pour te dire 'arrête'.",
"T’es tellement con que tu as besoin de GPS pour t’asseoir.",
"T’es tellement lent que les tortues te doublent en marchant.",
"T’es tellement froid que les igloos te demandent conseil.",
"T’es tellement idiot que même les plantes te fuient.",
"T’es tellement moche que ton reflet se cache derrière un rideau.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement faible que les moustiques t’attaquent.",
"T’es tellement ridicule que les clowns t’invitent à des cours.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement con que ton téléphone t’ignore.",
"T’es tellement nul que même ton chien refuse de te suivre.",
"T’es tellement bizarre que les fantômes t’ignorent.",
"T’es tellement fade que le sel te fuit.",
"T’es tellement lent que les limaces te doublent.",
"T’es tellement nul que même les araignées te craignent.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement ridicule que les escargots te battent au sprint.",
"T’es tellement paresseux que le canapé te quitte.",
"T’es tellement con que ton réveil te joue des tours.",
"T’es tellement nul que même ton Wi-Fi te bloque.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement lent que les escargots te doublent.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement idiot que les IA te regardent de travers.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que même les pigeons te fuient.",
"T’es tellement idiot que ton miroir se cache.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement nul que ton réveil te réveille pour te dire 'arrête'.",
"T’es tellement con que tu as besoin de GPS pour t’asseoir.",
"T’es tellement lent que les tortues te doublent en marchant."
"T’es tellement nul que même ton chien se moque de toi.",
"T’es tellement idiot que ton miroir demande des conseils.",
"T’es tellement froid que les igloos te trouvent tiède.",
"T’es tellement lent que les limaces te doublent au sprint.",
"T’es tellement moche que les poupées te fuient.",
"T’es tellement con que ton réveil te fait des blagues.",
"T’es tellement fade que le sel refuse de t’accompagner.",
"T’es tellement ridicule que les clowns t’invitent à leurs cours.",
"T’es tellement faible que même les feuilles te frappent.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement bizarre que ton ombre refuse de te suivre.",
"T’es tellement nul que les zombies te fuient.",
"T’es tellement idiot que même les plantes te regardent de travers.",
"T’es tellement moche que ton reflet se cache derrière un rideau.",
"T’es tellement lent que les tortues t’ont déjà dépassé.",
"T’es tellement con que ton téléphone t’ignore.",
"T’es tellement ridicule que les escargots te battent en course.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement paresseux que le canapé te fuit.",
"T’es tellement bizarre que les fantômes t’évitent.",
"T’es tellement nul que même les ordinateurs te bloquent.",
"T’es tellement idiot que les IA se moquent de toi.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te dépassent en marchant.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement con que même ton ombre te fuit.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que les pigeons t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement paresseux que même ton lit te quitte.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te dépassent.",
"T’es tellement nul que ton réveil se moque de toi.",
"T’es tellement idiot que même Google refuse de t’aider.",
"T’es tellement con que ton téléphone se déconnecte.",
"T’es tellement ridicule que les clowns t’invitent à des cours d’humour.",
"T’es tellement froid que les igloos te trouvent tiède.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement fade que le sel refuse de t’accompagner.",
"T’es tellement nul que même les araignées te fuient.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te doublent.",
"T’es tellement paresseux que ton canapé te quitte.",
"T’es tellement con que ton réveil te fait des tours.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement nul que les zombies t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement con que ton téléphone t’ignore.",
"T’es tellement ridicule que les escargots te battent en course.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement idiot que les IA se moquent de toi.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te dépassent.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement con que même ton ombre te fuit.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que les pigeons t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement paresseux que le canapé te fuit.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement nul que ton réveil se moque de toi.",
"T’es tellement idiot que même Google te fuit.",
"T’es tellement con que ton téléphone refuse de répondre.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement froid que les igloos te trouvent tiède.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement fade que le sel refuse de t’accompagner.",
"T’es tellement nul que même les araignées te fuient.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te doublent.",
"T’es tellement paresseux que ton canapé te quitte.",
"T’es tellement con que ton réveil te fait des tours.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement nul que les zombies t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement con que ton téléphone t’ignore.",
"T’es tellement ridicule que les escargots te battent en course.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement idiot que les IA se moquent de toi.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te dépassent.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement con que même ton ombre te fuit.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que les pigeons t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement paresseux que le canapé te fuit.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement nul que ton réveil se moque de toi.",
"T’es tellement idiot que même Google te fuit.",
"T’es tellement con que ton téléphone refuse de répondre.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement froid que les igloos te trouvent tiède.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement fade que le sel refuse de t’accompagner.",
"T’es tellement nul que même les araignées te fuient.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te doublent.",
"T’es tellement paresseux que ton canapé te quitte.",
"T’es tellement con que ton réveil te fait des tours.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement nul que les zombies t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement con que ton téléphone t’ignore.",
"T’es tellement ridicule que les escargots te battent en course.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement idiot que les IA se moquent de toi.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te dépassent.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement con que même ton ombre te fuit.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que les pigeons t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement paresseux que le canapé te fuit.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement nul que ton réveil se moque de toi.",
"T’es tellement idiot que même Google te fuit.",
"T’es tellement con que ton téléphone refuse de répondre.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement froid que les igloos te trouvent tiède.",
"T’es tellement bizarre que ton ombre te fuit.",
"T’es tellement fade que le sel refuse de t’accompagner.",
"T’es tellement nul que même les araignées te fuient.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te doublent.",
"T’es tellement paresseux que ton canapé te quitte.",
"T’es tellement con que ton réveil te fait des tours.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement nul que les zombies t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement con que ton téléphone t’ignore.",
"T’es tellement ridicule que les escargots te battent en course.",
"T’es tellement faible que les sacs de riz te repoussent.",
"T’es tellement nul que les ordinateurs t’ignorent.",
"T’es tellement idiot que les IA se moquent de toi.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement lent que les limaces te dépassent.",
"T’es tellement froid que les glaciers te trouvent tiède.",
"T’es tellement con que même ton ombre te fuit.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement nul que les pigeons t’ignorent.",
"T’es tellement idiot que ton miroir te juge.",
"T’es tellement bizarre que ton chat te fuit.",
"T’es tellement paresseux que le canapé te fuit.",
"T’es tellement faible que les moustiques te dominent.",
"T’es tellement moche que les poupées te craignent.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement nul que ton réveil se moque de toi.",
"T’es tellement idiot que même Google te fuit.",
"T’es tellement con que ton téléphone refuse de répondre.",
"T’es tellement ridicule que les clowns rient de toi."
"T’es tellement transparent que les fantômes te confondent avec un mur.",
"T’es tellement inutile que même un bouton de porte est plus utile que toi.",
"T’es tellement triste que les nuages te regardent avec pitié.",
"T’es tellement vieux jeu que ton portable te juge.",
"T’es tellement sec que les cactus te trouvent humide.",
"T’es tellement faux que les poupées refusent de te toucher.",
"T’es tellement brouillon que même tes notes se perdent.",
"T’es tellement silencieux que les mouches te survolent sans bruit.",
"T’es tellement paumé que ton GPS abandonne.",
"T’es tellement éteint que les lampes t’envient.",
"T’es tellement ridicule que les statues te rient au nez.",
"T’es tellement lent que l’ombre te double au soleil.",
"T’es tellement vide que les pots de fleurs te prennent pour un vase.",
"T’es tellement fade que le ketchup te fuit.",
"T’es tellement coincé que même ton ombre se bloque.",
"T’es tellement mou que les gelées te battent à l’élastique.",
"T’es tellement bizarre que les fantômes te prennent pour un monstre.",
"T’es tellement nul que même les robots t’ignorent.",
"T’es tellement froid que les pingouins te demandent des conseils de chaleur.",
"T’es tellement idiot que même ton chien te prend pour un ennemi.",
"T’es tellement laid que les miroirs te suppriment de leurs reflets.",
"T’es tellement maladroit que les murs portent plainte contre toi.",
"T’es tellement triste que les nuages pleurent pour toi.",
"T’es tellement fade que le sucre refuse de t’accompagner.",
"T’es tellement vide que les bouteilles te jugent.",
"T’es tellement bizarre que les statues te fuient.",
"T’es tellement faible que même le vent t’emporte.",
"T’es tellement lent que les escargots te doublent au sprint.",
"T’es tellement paresseux que ton lit s’échappe.",
"T’es tellement con que le dictionnaire te refuse une entrée.",
"T’es tellement inutile que les chaises se moquent de toi.",
"T’es tellement moche que les pierres te font un procès.",
"T’es tellement idiot que les plantes se moquent de toi.",
"T’es tellement silencieux que même les échos t’ignorent.",
"T’es tellement froid que le frigo te prend pour un congélateur.",
"T’es tellement ridicule que les clowns t’envoient des conseils.",
"T’es tellement lent que les tortues te battent aux courses.",
"T’es tellement bizarre que même les fantômes t’évitent.",
"T’es tellement faible que les souris te dominent.",
"T’es tellement vide que les bouteilles t’imitent.",
"T’es tellement mou que les gelées te surpassent.",
"T’es tellement maladroit que les murs te supplient d’arrêter.",
"T’es tellement triste que les nuages pleurent pour toi.",
"T’es tellement paumé que les GPS abandonnent.",
"T’es tellement fade que le sel refuse de te toucher.",
"T’es tellement inutile que même un caillou fait mieux.",
"T’es tellement vieux jeu que ton réveil te juge.",
"T’es tellement transparent que les fenêtres t’ignorent.",
"T’es tellement sec que les cactus te prennent pour un frère.",
"T’es tellement ridicule que les statues te prennent pour un bouffon.",
"T’es tellement con que les dictionnaires te suppriment des mots.",
"T’es tellement nul que les robots te bloquent.",
"T’es tellement bizarre que les fantômes t’évitent.",
"T’es tellement lent que l’ombre te dépasse.",
"T’es tellement faible que le vent t’emporte.",
"T’es tellement triste que les nuages pleurent à ta place.",
"T’es tellement paresseux que ton lit a pris un avocat contre toi.",
"T’es tellement idiot que même les plantes refusent de t’écouter.",
"T’es tellement mou que les gelées te surpassent.",
"T’es tellement maladroit que les murs demandent réparation.",
"T’es tellement vide que les bouteilles te copient.",
"T’es tellement fade que le ketchup te fuit.",
"T’es tellement bizarre que même les statues te fuient.",
"T’es tellement inutile que les chaises rient de toi.",
"T’es tellement con que le dictionnaire refuse ton nom.",
"T’es tellement moche que les pierres te rejettent.",
"T’es tellement idiot que les robots te fuient.",
"T’es tellement lent que les tortues te dépassent.",
"T’es tellement ridicule que les clowns t’envoient des leçons.",
"T’es tellement paumé que le GPS t’abandonne.",
"T’es tellement froid que le frigo te prend pour un glaçon.",
"T’es tellement silencieux que les échos t’ignorent.",
"T’es tellement faible que le vent te bat à plates coutures.",
"T’es tellement triste que même les nuages sont en larmes pour toi.",
"T’es tellement mou que les gelées te surpassent.",
"T’es tellement paresseux que le canapé te fuit.",
"T’es tellement bizarre que les fantômes te fuient.",
"T’es tellement vide que les bouteilles te copient.",
"T’es tellement inutile que même un caillou est plus utile que toi.",
"T’es tellement idiot que les plantes te prennent pour un parasite.",
"T’es tellement moche que les miroirs te suppriment de leurs reflets.",
"T’es tellement lent que les escargots te doublent au sprint.",
"T’es tellement ridicule que les clowns rient de toi.",
"T’es tellement paumé que ton GPS abandonne.",
"T’es tellement fade que le sel te fuit.",
"T’es tellement froid que les pingouins te jugent.",
"T’es tellement maladroit que les murs portent plainte contre toi.",
"T’es tellement con que le dictionnaire te supprime des entrées.",
"T’es tellement mou que les gelées te surpassent.",
"T’es tellement bizarre que même les statues te fuient.",
"T’es tellement inutile que les chaises te rient au nez.",
"T’es tellement idiot que même les robots te fuient.",
"T’es tellement triste que les nuages pleurent pour toi.",
"T’es tellement lent que les tortues te doublent.",
"T’es tellement ridicule que les clowns t’envoient des cours.",
"T’es tellement faible que le vent t’emporte.",
"T’es tellement paresseux que ton lit t’abandonne.",
"T’es tellement moche que les pierres te détestent.",
"T’es tellement fade que le ketchup te fuit.",
"T’es tellement paumé que le GPS abandonne.",
"T’es tellement froid que le frigo te juge.",
"T’es tellement silencieux que les échos t’ignorent."
];

// Commande punch
client.on('ready', () => {
  console.log(`✅ Connecté en tant que ${client.user.tag}`);
});

client.on('messageCreate', message => {
  if(message.content.startsWith('!punch')) {
    const mention = message.mentions.users.first();
    if(!mention) return message.reply("Tu dois mentionner quelqu'un !");

    const random = Math.floor(Math.random() * punchlines.length);
    message.channel.send(`${mention} ${punchlines[random]}`);
  }
});

client.login(process.env.TOKEN);
